version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - mongo
  mongo:
    image: mongo:3.6.23-xenial
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
    expose:
    - 27011
    ports:
    - 27011:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all"]
  app:
    build: .
    container_name: app
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    depends_on:
    - mongo
    ports:
    - 3000:3000
    restart: always
